### ISSUE TITLE
Bot run

### ISSUE THREAD

**Issue by sauravpandeyy** [shubhayu-64/Discord-Study-Bot#3]
Hey, Shubhayu!
What's the command to run the bot ?
I did python study-bot.py but it's showing no module named schedule
?? Please help!

**Comment by shubhayu-64** [comment]
Please share a screenshot of your error or paste the exact error.

**Comment by sauravpandeyy** [comment]
> Please share a screenshot of your error or paste the exact error.

Now it's showing like this 😑 
![Screenshot (124)](https://user-images.githubusercontent.com/83362803/124230187-4f468e00-db2c-11eb-8752-b3af282d5740.png)

**Comment by shubhayu-64** [comment]
Have you installed all requirements from requirements.txt? Try running pip install -r requirements.txt

**Comment by Sauravlol** [comment]
> Have you installed all requirements from requirements.txt? Try running pip install -r requirements.txt

![Screenshot (125)](https://user-images.githubusercontent.com/83362803/124231148-879a9c00-db2d-11eb-93b3-5e18b1d7b852.png)
Here!

**Comment by sauravpandeyy** [comment]
> Have you installed all requirements from requirements.txt? Try running pip install -r requirements.txt

                     ModuleNotFoundError : No module named 'schedule'

this is the error!

**Comment by sauravpandeyy** [comment]
@shubhayu-64  bro where are you?
help me!

**Comment by shubhayu-64** [comment]
Try pip install schedule

**Comment by sauravpandeyy** [comment]
thanks now it's working
but...
why I have to re-run the pip install -r requirements.txt line??
and i couldn't figure out the "RESTRICTED CHANNELS THING WHEN I JOIN THE MENTIONED CHANNELS" what's that?

**Comment by shubhayu-64** [comment]
You have to install the requirements.txt once to set up your system. 
The restricted channels are based on the settings of the role assigned. The role is meant to allow your access to only selected channels in the server once you are in the study room. When you leave, the role is removed and you get back access to all channels.

**Comment by sauravpandeyy** [comment]
Oh thnks!
It's reminding to upgrade pip to new version 21.1.3
What should I do?
Will it effect the code if i choose to upgrade it?? 
Now it's giving warning OUHH

**Comment by shubhayu-64** [comment]
You can upgrade if you wish to. It won't affect anything.

**Comment by sauravpandeyy** [comment]
> You can upgrade if you wish to. It won't affect anything.

Thanks :D
