### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by sauravpandeyy** [shubhayu-64/Discord-Study-Bot#6]
SyntaxError: Non-ASCII character '\xe2' in file study-bot.py on line 9, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

IDK what is this??
and why it is happening!

PLEASE HELP!

**Comment by shubhayu-64** [comment]
Please share your study-bot.py code.

**Comment by sauravpandeyy** [comment]
> Please share your study-bot.py code.

same code is there no changes 
 that line studyList = [
              '-----', '-----', ....
              ]

**Comment by shubhayu-64** [comment]
I cannot reproduce the issue on my end. Can you please share the exact code for me to take a look at? 
Also, share the screenshot of your error.

**Comment by sauravpandeyy** [comment]
![Screenshot (166)](https://user-images.githubusercontent.com/83362803/126862184-41cfe1ec-fbd8-444e-b750-9f66f7226de8.png)
![Screenshot (167)](https://user-images.githubusercontent.com/83362803/126862186-ca47a88c-95f0-4bac-bdcc-99bd9e2ba6a9.png)

**Comment by sauravpandeyy** [comment]
first one is error
second one is the code where error occured

**Comment by shubhayu-64** [comment]
I think there is some issue with your quotes.

Refer to this: https://stackoverflow.com/questions/25190659/syntaxerror-non-ascii-character-xe2/25191228

**Comment by sauravpandeyy** [comment]
thanks!
